name: Matrix workflow
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: self-hosted
    strategy:
      matrix:
        container: ["gradle:6-jdk8", "gradle:6-jdk11"]
    container:
      image: ${{ matrix.container }}   

    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
